"""add dataNasc in database

Revision ID: 403232694a83
Revises: 29f7d8017082
Create Date: 2024-08-09 18:36:12.157784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403232694a83'
down_revision: Union[str, None] = '29f7d8017082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dataNasc', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dataNasc')
    # ### end Alembic commands ###
